version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: database
    restart: always
    env_file:
      - local.env

    ports:
      - "3303:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:7.2
    container_name: redis-sep490
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .local.env
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network


  app:
    build: .
    container_name: be
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
#    environment:
#      SPRING-PROFILES-ACTIVE: local

    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:



#local: SPRING_PROFILE=local ./gradlew bootRun

#dev:
#-export SPRING_PROFILE=dev
#-docker-compose up --build

#prod:
#export SPRING_PROFILE=prod
#docker-compose up --build -d